tunnel: e2e3bfc1-235f-40fe-9b6c-99da3e9bf268
credentials-file: /etc/cloudflared/e2e3bfc1-235f-40fe-9b6c-99da3e9bf268.json

ingress:
  - hostname: collembola.advandeb.com
    service: http://localhost:9000
  - hostname: ai.advandeb.com
    service: http://localhost:3000
  - hostname: reproduction.advandeb.com
    service: http://localhost:5000
  - hostname: testreproduction.advandeb.com
    service: http://localhost:5001
  - hostname: ollama.advandeb.com
    service: http://localhost:11434
  - hostname: advandeb.com
    service: http://localhost:9100
  - service: http_status:404
